### ISSUE TITLE
Get result from scenario in afterScenario hook

### ISSUE THREAD

**Issue by MarekSlaninka** [Tyler-Keith-Thompson/CucumberSwift#29]
Hello,

is it possible to get result of scenario, in afterScenario hook? I need it for reporting results to TestRail. At the moment a can not find any option to get the result.

Thank You

**Comment by Tyler-Keith-Thompson** [comment]
Interesting! So CucumberSwift has its own report, and it has its own reporter class. What I could very reasonably do is provide hooks for you. The AfterScenario hook may be a bad place since it's designed for cleanup. 

I'll see what I can do this weekend to expose an API for you to tie into events to report it however you'd like. You could also set up your own `XCTestObserver` if you needed something *today* but I think I can give you a much better experience than that.

**Comment by MarekSlaninka** [comment]
That would be great, thank you very much :)

**Comment by Tyler-Keith-Thompson** [comment]
Alright CucumberSwift v3.1.12 adds this: I've also added [some docs](https://github.com/Tyler-Keith-Thompson/CucumberSwift/wiki/Custom-Reporters) to showcase how it works. 

I'll leave this open to make sure it satisfies your needs.

**Comment by MarekSlaninka** [comment]
Hi, this looks pretty great. But was it necessary to bump minimum iOS version to 13?

**Comment by Tyler-Keith-Thompson** [comment]
Annoyingly, it has everything to do with the duration. Apparently it won't let me use .nanoseconds without iOS 13. 

I can back that out and just use a double, or write something custom to try and bring back support for .nanoseconds on older versions if anybody needs it.

**Comment by MarekSlaninka** [comment]
If you just use TimeInterval, which is alias for Double? The problem is, our application support iOS 12, and it will be supported till release of iOS 15.

**Comment by Tyler-Keith-Thompson** [comment]
Just goes to show I should not make assumptions on behalf of my users. I will get you an iOS 12 compatible version ASAP

**Comment by Tyler-Keith-Thompson** [comment]
CucumberSwift 3.2.2 should reasonably solve your problem. Minimum iOS target of 10.

**Comment by MarekSlaninka** [comment]
Thank You again :)
