### ISSUE TITLE
Steps separated as rT and Command line support 

### ISSUE THREAD

**Issue by ysnnzlcn** [Tyler-Keith-Thompson/CucumberSwift#54]
Hi, i am trying to implement this to my project but there are some concepts that i can't understand. I read the docs and checked the CucumberSwiftSample but it didnt help.

How i use it:
<img width="1046" alt="Screen Shot 2022-11-02 at 10 12 36" src="https://user-images.githubusercontent.com/30194773/199424542-a15c5041-8bff-47b7-89df-26b6536cd449.png">

As you can see in the image I defined steps inside the test func and expect them to be grouped in the test results with a big T but every single step looks like they are a separate test. My questions are:
* Is there a way to group them under the func name? Why does every step look like another test case?
* Is it possible to run any test seperately? Right now if i run any test separately, it gets succeeded without running cucumber steps but if i run them all (cmd+U) cucumber works.
* When i run tests from the terminal and CI/CD, cucumber also doesn't work. Is there a documentation to follow for this implementation?

**Comment by Tyler-Keith-Thompson** [comment]
Apologies for the late response, I've had some surgeries that took me out of commission for quite a while. 

**Q: Is there a way to group them under the func name? Why does every step look like another test case?**
A: Because XCTest is not even remotely friendly to tie into. The only way to do it is to use the Objective-C runtime and dynamically create classes. So that's what CucumberSwift does. This causes all of the behaviors you've witnessed. There isn't a way to group them per se...but there are 3 workarounds. 
  - You can use the report navigator in Xcode to see a much better grouping of features/scenarios/steps.
  - You can use the Cucumber Report (JSON format, but there are renderers). This looks the best.
  - You can use the DSL with your own XCTestCase classes, much like you'd write any other kind of test. The downside here is that you can't use `.feature` files, which depending on your team structure and desire to work with other Cucumber implementations, might not be practical.
  
**Q: Is it possible to run any test seperately? Right now if i run any test separately, it gets succeeded without running cucumber steps but if i run them all (cmd+U) cucumber works.**
A: Yeah, that's because the classes are dynamically created, and so `rerun` can't actually find the class to run. There is a workaround with the [shouldRun](https://github.com/Tyler-Keith-Thompson/CucumberSwift/wiki/run-by-line) method. NOTE: This will be moved to DocC when I have time. These docs show how you can run by line number, but you have the scenario object, so run by whatever criteria you want, tags, line, scenario title, whatever.

**Q: When i run tests from the terminal and CI/CD, cucumber also doesn't work. Is there a documentation to follow for this implementation?**
A: That's weird...I run by CI/CD all the time. In fact this whole library can only deploy if that works. I'd need way more info on what you're trying to do. Short answer: If you use xcodebuild to run your tests, you should be fine.

**Comment by ysnnzlcn** [comment]
@Tyler-Keith-Thompson No problem man, thank you for responding. I have handled the terminal issue and will try your suggestions. I will close this issue and reopen it if i get stuck in the future. Thanks again 🙏
