### ISSUE TITLE
XCTestCase ContinueAfterFailure behavior

### ISSUE THREAD

**Issue by olyv** [Tyler-Keith-Thompson/CucumberSwift#9]
There is a wiki page describing how to use [ContinueAfterFailure](https://github.com/Tyler-Keith-Thompson/CucumberSwift/wiki/XCTest-Integration) property of XCTestCase but I would like to clarify once again if it works as intended. What I would like to achieve is to step test execution immediately upon failed assertion. As I can see current implementation of CucumberSwift allows me only to stop scenario execution while the step continue running. This artificial example can demonstrate the issue I am facing now:
```
public var continueTestingAfterFailure:Bool {
    return false
 }

MatchAll("^some step definition$") { _, step in
         XCTFail("I would like to stop now")
         var foo:String?
         print("but it's going to be a fatal error \(foo!)")
      }
```
while below implementation stops immediately
```
MatchAll("^some step definition$") { _, step in
         step.continueAfterFailure = false
         XCTFail("indeed stops now")
         var foo:String?
         print("not reachable statement \(foo!)")
      }
```
And I wonder if existing implementation of CucumberSwift assumed existing behavior of  `step.continueAfterFailure = false`?

**Comment by Tyler-Keith-Thompson** [comment]
Pretty sure I've identified the problem, this one isn't something I know how to write a test for...so we'll have to go off of my manual tests. That's particular unfortunate because this was an order-of-operations kind of thing, which automated tests are pretty good at helping prevent.

This should be fixed as of 2.2.8. I'm going to close assuming my manual tests did the trick, feel free to open another issue if you encounter any problems.
